/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CarbonChevronLeft: typeof import('~icons/carbon/chevron-left')['default']
    Note: typeof import('./src/components/Note.vue')['default']
    Paper: typeof import('./src/components/Paper.vue')['default']
    PlaygroundX: typeof import('./src/components/PlaygroundX.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Toggle: typeof import('./src/components/Toggle.vue')['default']
    Turns: typeof import('./src/components/Turns.vue')['default']
  }
}
